## General process of a supervised machine learning

In [ ]:
#supervised: have labels

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# Create a linear regression model
model = LinearRegression(normalize = True) #linear regression is a class name, just imported a class called linear regression
                                            #create an instance of the linear regression model
                                            #specify hyperparameter normalize to be true. Depends on model to tune models.
print(model) #tells me what the parameters are

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)


In [2]:
# Create toy data
X, y = np.arange(10).reshape((5,2)),range(5)
X #X all of features. y is the range from 0 to 5. 
#Convention to use uppercase X for MATRIX. 5x2 here
#y is lowercase. lowercase for vector or series.vector of 5 values

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [3]:
# y is a range, so we have to cast to list to see the items inside
list(y)

[0, 1, 2, 3, 4]

In [4]:
# Split the training set and the testing set
# in this case, 40% of the samples are used for testing.
# Run this cell again to shuffle and split again.
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.4)
#is train split a function or method? It is a function. Send X, y, and test size of 40%. Hold 40% samples as testing set.
#returns for things: X_train, X_test, y_train, y_test
X_train



array([[2, 3],
       [6, 7],
       [8, 9]])

In [5]:
y_train #labels of training set

[1, 3, 4]

In [6]:
X_test

array([[0, 1],
       [4, 5]])

In [7]:
y_test

[0, 2]

In [9]:
model.fit(X_train, y_train)
#this model is the linear regression model we just created
#is this fit a function or a method? This a method b/c we did a instance.methodname or object.methodname
#want to send X_train,y_train to linear regression model for training

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)

In [11]:
# Only print two digits after the decimal
predictions = model.predict(X_test)
#another method call. Get predictions based off X_test
predictions #2.02e-15 (VERY SMALL)


array([2.02615702e-15, 2.00000000e+00])

In [16]:
np.set_printoptions(precision=2) #ony keep 2 digits after decimal


In [17]:
predictions

array([2.03e-15, 2.00e+00])

## To sum up:
- import the model from sklearn
- create an instance of the model
    - you may need to specify parameter(s)
- train_test_split will take the features (usually X) and vales/lables (usually as y)
- train_test_split will return a 4-object tuple
- call *fit* function will "train" your model
- call *predict* function to make predictions with the testing set

In [ ]:
#ML getting cheaper
#datascientist still getting good salary
'''Spend time on:
    1. Aquiring data
        Get access to data (Jump through hoops)
    2. Data is not clean
    3. Model tuning
        Have to specify lots of parameters in order to get reasonable results
    4.Evaluating Model
        
    